### ISSUE TITLE
Error when launching ./run_sim.sh

### ISSUE THREAD

**Issue by DavidYaonanZhu** [abizovnuralem/go2_omniverse#14]
Error occurs when running the simulation,

[Error] [omni.ext.plugin] Failed to resolve extension dependencies. Failure hints:
 Synced registries:
	 - kit/default         : found 502 packages 
	 - kit/sdk             : found 624 packages 
	 - kit/community       : found 342 packages 

this error stops the simulation from running.

Ubuntu 22.04, Isaac 4.0, conda isaaclab environment.

Best regards

**Comment by DavidYaonanZhu** [comment]
Follwoing these errors:

[8.560s] [ext: omni.kit.xr.system.openxr-106.0.50] startup
Error [GENERAL |  | OpenXR-Loader] : RuntimeManifestFile::FindManifestFiles - failed to determine active runtime file path for this environment
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - unknown error
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - failed to load a runtime
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed to find default runtime with RuntimeInterface::LoadRuntime()
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed querying extension properties

**Comment by abizovnuralem** [comment]
Hello, Have you tried to verify the installation? 
https://isaac-sim.github.io/IsaacLab/source/setup/installation/verifying_installation.html
python source/standalone/tutorials/00_sim/create_empty.py

**Comment by abizovnuralem** [comment]
What is the conda name are you using?

**Comment by abizovnuralem** [comment]
I can suggest you manually repeat all the steps from ./run_sim.sh
source /opt/ros/${ROS_DISTRO}/setup.bash
cd IsaacSim-ros_workspaces/${ROS_DISTRO}_ws
rosdep install --from-paths src --ignore-src -r -y
colcon build
source install/setup.bash
cd ../..
cd go2_omniverse_ws
rosdep install --from-paths src --ignore-src -r -y
colcon build
source install/setup.bash
cd ..

eval "$(conda shell.bash hook)"
conda activate isaaclab
export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6

# Run the Python script
python main.py --robot_amount 1 --robot go2
and see at what step do you have a problem

**Comment by DavidYaonanZhu** [comment]
OK, let me try

**Comment by DavidYaonanZhu** [comment]
> What is the conda name are you using?

I am using the isaaclab, the one tat I set up following the official instructions

**Comment by DavidYaonanZhu** [comment]
Hi, I have manually run all the commands in the shell script.

The simulation runs successfully.

At the mean time I need to fix several dependency errors during the process.

1. AttributeError: module 'em' has no attribute 'BUFFERED_OPT', solved by `pip install empy==3.3.4`
2. ModuleNotFoundError: No module named 'lark', solved by `pip3 install lark`

While, the original error regarding the isaac kit still remains.

Best regards

**Comment by abizovnuralem** [comment]
Got it, I have removed the VR from the code, can you try again please?

**Comment by DavidYaonanZhu** [comment]
Hi, I tried the new fix.

The kit error disapperd,

But for some reason, the shell script doesn't work, it starts the sim but the sim will close immediately.

To run the sim, I have to run the command step by step.

Best regards

**Comment by abizovnuralem** [comment]
Can you send me a short video or image of how you started the script?

**Comment by DavidYaonanZhu** [comment]
Hi, I found the problem is that I run the shell script with isaaclab env already activated.
Once I turn off the isaaclab env, the shell works fine.

Thanks!

Btw, there are some minor issues regarding G1,
1. The camera view point is from the roof top, not from head pointing front.
2. The pointcloud from G1 can not be displayed on rviz.
3. Which balancing algorithm do you use? And how did you train them?
4. Do you have some instructions regarding motion control?

Best regards

**Comment by DavidYaonanZhu** [comment]
Hi, @abizovnuralem
Thanks for your help, and I’m glad I could debug.
May I know the URL of your example in isaaclab for balance control?

Best regards.

**Comment by abizovnuralem** [comment]
This is it: https://github.com/isaac-sim/IsaacLab/pull/453

**Comment by DavidYaonanZhu** [comment]
Thanks!





------------------ Original ------------------
From: Brimo ***@***.***&gt;
Date: Mon,Jun 17,2024 8:18 PM
To: abizovnuralem/go2_omniverse ***@***.***&gt;
Cc: Weyland Yutani ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [abizovnuralem/go2_omniverse] Error when launching ./run_sim.sh(Issue #14)





 
This is it: isaac-sim/IsaacLab#453
