### ISSUE TITLE
RslRlVecEnvWrapper

### ISSUE THREAD

**Issue by jhzioeng** [abizovnuralem/go2_omniverse#24]
Traceback (most recent call last):
  File "/home/qy/git/go2_omniverse/main.py", line 29, in <module>
    run_sim()
  File "/home/qy/git/go2_omniverse/omniverse_sim.py", line 191, in run_sim
    env = RslRlVecEnvWrapper(env)
TypeError: Can't instantiate abstract class RslRlVecEnvWrapper with abstract method get_privileged_observations

when I run ./run_sim.sh the Isaac Sim started, I can see the dog, but can't see the environment.

**Comment by abizovnuralem** [comment]
is it IsaacSim 4.0?

**Comment by jhzioeng** [comment]
> is it IsaacSim 4.0?

Well，It works. （with IsaacSim4.0 which instead 4.1)  You're absolutely right!

**Comment by KailinTong** [comment]
Hello, I was faced with the exact same error, but I use isaacSim 2023.1.1, shall I also try IsaacSim 4.0?
