### ISSUE TITLE
Nav2 unable to work when I set a waypoint in Rviz

### ISSUE THREAD

**Issue by brandon-lawrence96** [abizovnuralem/go2_omniverse#39]
Hi,

I have followed all the instructions in the repo. I can run slam_toolbox and generate a map but in rviz. However, after launching the nav2 stack, and setting a waypoint in rviz, the robot just starts spinning and I get this output in my terminal: 
[planner_server-3] [INFO] [1726041059.837395072] [global_costmap.global_costmap]: StaticLayer: Resizing costmap to 228 X 285 at 0.050000 m/pix
[bt_navigator-5] [INFO] [1726041090.097915329] [bt_navigator]: Begin navigating from current location (-1.19, 0.13) to (-0.57, 0.08)
[controller_server-1] [INFO] [1726041090.119311395] [controller_server]: Received a goal, begin computing control effort.
[controller_server-1] [WARN] [1726041090.119379408] [controller_server]: No goal checker was specified in parameter 'current_goal_checker'. Server will use only plugin loaded general_goal_checker . This warning will appear once.
[controller_server-1] [INFO] [1726041091.169673668] [controller_server]: Passing new path to controller.
[controller_server-1] [INFO] [1726041092.219678067] [controller_server]: Passing new path to controller.
[controller_server-1] [INFO] [1726041093.219670780] [controller_server]: Passing new path to controller.
[controller_server-1] [INFO] [1726041094.271476080] [controller_server]: Passing new path to controller.
[controller_server-1] [INFO] [1726041095.269679048] [controller_server]: Passing new path to controller.
[controller_server-1] [INFO] [1726041096.319674218] [controller_server]: Passing new path to controller.
[controller_server-1] [INFO] [1726041097.369673757] [controller_server]: Passing new path to controller.
[controller_server-1] [INFO] [1726041098.369670088] [controller_server]: Passing new path to controller.
[controller_server-1] [INFO] [1726041099.419681132] [controller_server]: Passing new path to controller.
[controller_server-1] [ERROR] [1726041100.119737493] [controller_server]: Failed to make progress
[controller_server-1] [WARN] [1726041100.119831207] [controller_server]: [follow_path] [ActionServer] Aborting handle.
[controller_server-1] [INFO] [1726041100.138259863] [local_costmap.local_costmap]: Received request to clear entirely the local_costmap
[controller_server-1] [INFO] [1726041100.139099084] [controller_server]: Received a goal, begin computing control effort.
[controller_server-1] [WARN] [1726041100.234222488] [controller_server]: Control loop missed its desired rate of 20.0000Hz
[planner_server-3] [ERROR] [1726041100.701640634] [transformPoseInTargetFrame]: Extrapolation Error looking up target frame: Lookup would require extrapolation into the past.  Requested time 1726041090.097010 but the earliest data is at time 1726041090.747207, when looking up transform from frame [odom] to frame [map]
[planner_server-3] 
[planner_server-3] [WARN] [1726041100.701680023] [planner_server]: Could not transform the start or goal pose in the costmap frame
[planner_server-3] [WARN] [1726041100.701716398] [planner_server]: [compute_path_to_pose] [ActionServer] Aborting handle.
[planner_server-3] [INFO] [1726041100.718213496] [global_costmap.global_costmap]: Received request to clear entirely the global_costmap
[controller_server-1] [INFO] [1726041100.739308276] [controller_server]: Passing new path to controller.
[controller_server-1] [ERROR] [1726041100.739474391] [controller_server]: Invalid path, Path is empty.
[controller_server-1] [WARN] [1726041100.739515000] [controller_server]: [follow_path] [ActionServer] Aborting handle.
[bt_navigator-5] [ERROR] [1726041100.788673259] [bt_navigator_navigate_to_pose_rclcpp_node]: Failed to get result for compute_path_to_pose in node halt!
[controller_server-1] [INFO] [1726041100.788923462] [local_costmap.local_costmap]: Received request to clear entirely the local_costmap
[planner_server-3] [INFO] [1726041100.789555790] [global_costmap.global_costmap]: Received request to clear entirely the global_costmap
[bt_navigator-5] [WARN] [1726041100.790108806] [BehaviorTreeEngine]: Behavior Tree tick rate 100.00 was exceeded!
[planner_server-3] [ERROR] [1726041101.153598378] [transformPoseInTargetFrame]: Extrapolation Error looking up target frame: Lookup would require extrapolation into the past.  Requested time 1726041090.097010 but the earliest data is at time 1726041091.149766, when looking up transform from frame [odom] to frame [map]
[planner_server-3] 
[planner_server-3] [WARN] [1726041101.153641290] [planner_server]: Could not transform the start or goal pose in the costmap frame
[planner_server-3] [WARN] [1726041101.153673540] [planner_server]: [compute_path_to_pose] [ActionServer] Aborting handle.
[planner_server-3] [INFO] [1726041101.168628444] [global_costmap.global_costmap]: Received request to clear entirely the global_costmap
[planner_server-3] [ERROR] [1726041102.141661091] [transformPoseInTargetFrame]: Extrapolation Error looking up target frame: Lookup would require extrapolation into the past.  Requested time 1726041090.097010 but the earliest data is at time 1726041092.165796, when looking up transform from frame [odom] to frame [map]
[planner_server-3] 
[planner_server-3] [WARN] [1726041102.141733732] [planner_server]: Could not transform the start or goal pose in the costmap frame
[planner_server-3] [WARN] [1726041102.141762539] [planner_server]: [compute_path_to_pose] [ActionServer] Aborting handle.
[behavior_server-4] [INFO] [1726041102.160766023] [behavior_server]: Running spin
[behavior_server-4] [INFO] [1726041102.160931650] [behavior_server]: Turning 1.57 for spin behavior.
[planner_server-3] [INFO] [1726041109.837430692] [global_costmap.global_costmap]: StaticLayer: Resizing costmap to 250 X 305 at 0.050000 m/pix
[behavior_server-4] [WARN] [1726041112.161082170] [behavior_server]: Exceeded time allowance before reaching the Spin goal - Exiting Spin
[behavior_server-4] [WARN] [1726041112.161126943] [behavior_server]: spin failed
[behavior_server-4] [WARN] [1726041112.161153445] [behavior_server]: [spin] [ActionServer] Aborting handle.
[behavior_server-4] [INFO] [1726041112.180591351] [behavior_server]: Running wait
[planner_server-3] [INFO] [1726041114.837402103] [global_costmap.global_costmap]: StaticLayer: Resizing costmap to 269 X 328 at 0.050000 m/pix
[behavior_server-4] [INFO] [1726041117.180781628] [behavior_server]: wait completed successfully
[planner_server-3] [ERROR] [1726041117.516774487] [transformPoseInTargetFrame]: Extrapolation Error looking up target frame: Lookup would require extrapolation into the past.  Requested time 1726041090.097010 but the earliest data is at time 1726041107.509879, when looking up transform from frame [odom] to frame [map]
[planner_server-3] 
[planner_server-3] [WARN] [1726041117.516811434] [planner_server]: Could not transform the start or goal pose in the costmap frame
[planner_server-3] [WARN] [1726041117.516844368] [planner_server]: [compute_path_to_pose] [ActionServer] Aborting handle.
[planner_server-3] [INFO] [1726041117.530308937] [global_costmap.global_costmap]: Received request to clear entirely the global_costmap
[planner_server-3] [ERROR] [1726041118.143420117] [transformPoseInTargetFrame]: Extrapolation Error looking up target frame: Lookup would require extrapolation into the past.  Requested time 1726041090.097010 but the earliest data is at time 1726041108.220414, when looking up transform from frame [odom] to frame [map]
[planner_server-3] 
[planner_server-3] [WARN] [1726041118.143456826] [planner_server]: Could not transform the start or goal pose in the costmap frame
[planner_server-3] [WARN] [1726041118.143484774] [planner_server]: [compute_path_to_pose] [ActionServer] Aborting handle.
[behavior_server-4] [INFO] [1726041118.160676565] [behavior_server]: Running backup

----------------------------------------------------------------------------------------------------

I also notice that when I echo the /plan topic the header has no time and no frame_id as seen here:
- header:
    stamp:
      sec: 0
      nanosec: 0
    frame_id: ''
  pose:
    position:
      x: -1.2882789517265012
      y: 0.08675722978059491
      z: 0.0037457583775203085
    orientation:
      x: 0.004655587162568282
      y: -0.002729972258295249
      z: 0.9107078357332794
      w: -0.4130158722054724
---------------------------------------------------------------------------------------------------------
 This seems weird. Would appreciate your help in this. Thank you.

From,
Brandon

**Comment by abizovnuralem** [comment]
Hello! I can suggest debugging ros2 topics that are publishing cmd commands to the dog, about time we have an open issue https://github.com/abizovnuralem/go2_omniverse/issues/19 I will be happy for your pr!

**Comment by brandon-lawrence96** [comment]
Hi. Thank you for your swift reply. Do you suggest that I do what [richard98hess444] suggested?

**Comment by abizovnuralem** [comment]
It would be best if you put true for use_sim_time I guess, also yeah, you can try richard98hess444 suggestion. About ros2 topic debug just use rqt_graph and then ros2 topic echo

**Comment by abizovnuralem** [comment]
If you still have an issue just reopen it, thanks!
