### ISSUE TITLE
Sensor HZ Adjustment

### ISSUE THREAD

**Issue by cyhunblr** [abizovnuralem/go2_omniverse#50]
I tried almost everything but I couldn't get the IMU sensor to work at around ~200HZ or the 3D LiDAR sensor to work at around ~10Hz. Is there any solution?

**Comment by abizovnuralem** [comment]
Hello! How do you count HZ?

**Comment by cyhunblr** [comment]
> Hello! How do you count HZ?

ros2 topic hz /imu_topic or /pointcloud_topic
By the way, I found this on the forum: https://forums.developer.nvidia.com/t/imu-topic-publish-code-error/247641.

**Comment by abizovnuralem** [comment]
If you have additional questions, please open a new issue, thanks!
