### ISSUE TITLE
IsaacSim 2023.1.1 no longer available

### ISSUE THREAD

**Issue by delenius** [abizovnuralem/go2_omniverse#54]
It is no longer possible to install this from the Omniverse launcher, only version 4.0.0 and up.
Should we expect the newer versions to work, or are you planning support for those?
(Or is it possible to get the older version somewhere?).

**Comment by abizovnuralem** [comment]
Hello, @delenius ! Can you check readme  please? We have posted a detailed instructions on how to get 2023.1.1 in Troubleshooting , feel free to contact me if you need any additional help
